export const START_RANDOM_GITHUB_USERS = "START_RANDOM_GITHUB_USERS";
export const SUCCESS_RANDOM_GITHUB_USERS = "SUCCESS_RANDOM_GITHUB_USERS";
export const FAILURE_RANDOM_GITHUB_USERS = "FAILURE_RANDOM_GITHUB_USERS";

export const START_MY_USER_PROFILE = "START_MY_USER_PROFILE";
export const SUCCESS_MY_USER_PROFILE = "SUCCESS_MY_USER_PROFILE";
export const FAILURE_MY_USER_PROFILE = "FAILURE_MY_USER_PROFILE";

export const RESET_REDUCER = "RESET_REDUCER";
